# lxc-wireguard.tf - WireGuard VPN tunnel LXC container
#
# Lightweight LXC running WireGuard as a VPN endpoint for remote
# LAN access. Connects phone/laptop from anywhere and routes traffic
# to the 192.168.86.0/24 network via IP forwarding + masquerade.
#
# Extremely lightweight: WireGuard is a kernel module, minimal userspace.
# No Docker needed -- WireGuard runs natively on the host.
#
# VPN subnet: 10.10.0.0/24
# Server: 10.10.0.1, clients: 10.10.0.2+
# UDP port: 51820
#
# Requires:
#   - Port forward on Google Nest: UDP 51820 -> 192.168.86.39
#   - Client configs generated by the setup playbook

resource "proxmox_virtual_environment_container" "wireguard" {
  node_name   = lookup(var.node_assignments, "wireguard", var.proxmox_node)
  vm_id       = var.wireguard_vmid
  description = "WireGuard - VPN tunnel for remote LAN access"
  tags        = ["infrastructure", "vpn", "security"]

  unprivileged  = false  # Needs access to kernel WireGuard module
  started       = true
  start_on_boot = true

  operating_system {
    template_file_id = var.debian_template
    type             = "debian"
  }

  cpu {
    cores = 1
    units = 512  # Minimal -- kernel WireGuard, near-zero overhead
  }

  memory {
    dedicated = 256
  }

  disk {
    datastore_id = var.lxc_storage
    size         = 2
  }

  network_interface {
    name   = "eth0"
    bridge = var.network_bridge
  }

  # Static IP, DNS, and SSH key for Ansible access
  initialization {
    hostname = "wireguard"

    ip_config {
      ipv4 {
        address = "${var.wireguard_ip}/${var.network_subnet}"
        gateway = var.network_gateway
      }
    }

    dns {
      servers = var.nameservers
    }

    user_account {
      keys = var.ssh_public_key != "" ? [var.ssh_public_key] : []
    }
  }

  lifecycle {
    # These are creation-time attributes that Terraform can't read back
    # from an imported container. Ignoring prevents destroy/recreate drift.
    ignore_changes = [
      unprivileged,
      operating_system[0].template_file_id,
      initialization[0].user_account,
    ]
  }
}
