http:
  routers:
    truenas:
      rule: "Host(`nas.woodhead.tech`)"
      entryPoints:
        - websecure
      service: truenas
      tls:
        certResolver: cloudflare
        domains:
          - main: "*.woodhead.tech"
      middlewares:
        - authentik@file

  services:
    truenas:
      loadBalancer:
        servers:
          - url: "https://192.168.86.40"
        passHostHeader: false
        serversTransport: truenas-transport

  serversTransports:
    truenas-transport:
      insecureSkipVerify: true
