{
 "title": "Proxmox via Prometheus",
 "description": "Proxmox Virtual Environment Dashboard",
 "tags": [
  "Proxmox",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(pve_node_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Resource allocation summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (id, name, type) (pve_guest_info{instance=\"$instance\",template!=\"1\"})"
    },
    {
     "expr": "sum by (id) (pve_up{instance=\"$instance\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_limit{instance=\"$instance\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_size_bytes{instance=\"$instance\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_usage_bytes{instance=\"$instance\"} / pve_memory_size_bytes and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_disk_size_bytes{instance=\"$instance\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_disk_usage_bytes{instance=\"$instance\"} / pve_disk_size_bytes and on (id, instance) pve_guest_info)"
    }
   ]
  },
  {
   "title": "Host CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{instance=\"$instance\", id=~\"node/.+\"}/pve_cpu_usage_limit{instance=\"$instance\", id=~\"node/.+\"}"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{instance=\"$instance\", id=~\"node/.+\"}/pve_memory_size_bytes{instance=\"$instance\", id=~\"node/.+\"}"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{instance=\"$instance\", id=~\"storage/.+\"}/pve_disk_size_bytes{instance=\"$instance\", id=~\"storage/.+\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Space allocation",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(pve_disk_size_bytes{instance=\"$instance\", id=~\"storage/.+\"}, \"legend\", \"$2\", \"id\", \"^([^\\\\/]+\\\\/)*([^\\\\/]+)$\")",
     "legendFormat": "{{legend}}"
    }
   ]
  },
  {
   "title": "Guests Disk usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{instance=\"$instance\"}/pve_disk_size_bytes{instance=\"$instance\"} and on(id, instance) pve_guest_info",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Guests CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{instance=\"$instance\"}/pve_cpu_usage_limit and on(id, instance) pve_up == 1",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Guests memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{instance=\"$instance\"}/pve_memory_size_bytes and on(id, instance) pve_up == 1",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Network IO/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(pve_network_receive_bytes{instance=\"$instance\"}[5m]) and on(id, instance) pve_up == 1",
     "legendFormat": "{{id}} RECV"
    },
    {
     "expr": "rate(pve_network_transmit_bytes{instance=\"$instance\"}[5m]) and on(id, instance) pve_up == 1",
     "legendFormat": "{{id}} SEND"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(pve_disk_write_bytes{instance=\"$instance\"}[5m])+rate(pve_disk_read_bytes[5m]) and on(id, instance) pve_up == 1",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}