{
 "title": "UPS Monitoring",
 "tags": [
  "ups",
  "power",
  "nut"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "tc3 Battery Charge",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{instance=\"ups-thinkcentre3\"}",
     "legendFormat": "tc3"
    }
   ]
  },
  {
   "title": "tower1 Battery Charge",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{instance=\"ups-tower1\"}",
     "legendFormat": "tower1"
    }
   ]
  },
  {
   "title": "zotac Battery Charge",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{instance=\"ups-zotac\"}",
     "legendFormat": "zotac"
    }
   ]
  },
  { "title": "thinkcentre3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{instance=\"ups-thinkcentre3\"}",
     "legendFormat": "Battery %"
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{instance=\"ups-thinkcentre3\"}",
     "legendFormat": "Load %"
    }
   ]
  },
  {
   "title": "Runtime Remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{instance=\"ups-thinkcentre3\"}",
     "legendFormat": "Runtime"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status{instance=\"ups-thinkcentre3\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{instance=\"ups-thinkcentre3\"}",
     "legendFormat": "Input V"
    },
    {
     "expr": "network_ups_tools_battery_voltage{instance=\"ups-thinkcentre3\"}",
     "legendFormat": "Battery V"
    },
    {
     "expr": "network_ups_tools_output_voltage{instance=\"ups-thinkcentre3\"}",
     "legendFormat": "Output V"
    }
   ]
  },
  { "title": "tower1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{instance=\"ups-tower1\"}",
     "legendFormat": "Battery %"
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{instance=\"ups-tower1\"}",
     "legendFormat": "Load %"
    }
   ]
  },
  {
   "title": "Runtime Remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{instance=\"ups-tower1\"}",
     "legendFormat": "Runtime"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status{instance=\"ups-tower1\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{instance=\"ups-tower1\"}",
     "legendFormat": "Input V"
    },
    {
     "expr": "network_ups_tools_battery_voltage{instance=\"ups-tower1\"}",
     "legendFormat": "Battery V"
    },
    {
     "expr": "network_ups_tools_output_voltage{instance=\"ups-tower1\"}",
     "legendFormat": "Output V"
    }
   ]
  },
  { "title": "zotac", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{instance=\"ups-zotac\"}",
     "legendFormat": "Battery %"
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{instance=\"ups-zotac\"}",
     "legendFormat": "Load %"
    }
   ]
  },
  {
   "title": "Runtime Remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{instance=\"ups-zotac\"}",
     "legendFormat": "Runtime"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status{instance=\"ups-zotac\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{instance=\"ups-zotac\"}",
     "legendFormat": "Input V"
    },
    {
     "expr": "network_ups_tools_battery_voltage{instance=\"ups-zotac\"}",
     "legendFormat": "Battery V"
    },
    {
     "expr": "network_ups_tools_output_voltage{instance=\"ups-zotac\"}",
     "legendFormat": "Output V"
    }
   ]
  }
 ]
}