baseURL = 'https://resume.woodhead.tech/'
locale = 'en-us'
title = 'Brandon Woodward'
theme = ''

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "Systems Engineer | Homelab Enthusiast"
